import styles from '@/styles/Home.module.css';
import { block } from 'million/react';
import Head from 'next/head';
import { Suspense, useState } from 'react';

// change and ni every time for every change
//     "million": "file:/Users/aidenybai/Projects/aidenybai/million",

function Img() {
  return <div>1</div>;
}

function Button() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <Img />
      <button onClick={() => setCount(count + 1)}>{count}</button>
    </div>
  );
}

const ButtonBlock = block(Button);

// throw new Error(ButtonBlock);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        test
        <ButtonBlock />
      </main>
    </>
  );
}
