import styles from '@/styles/Home.module.css';
import { block } from 'million/react';
import Head from 'next/head';
import { useState } from 'react';
import Image from 'next/legacy/image';

function Img() {
  return <div>hi</div>;
}

function Button() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <div>
        <Img />
      </div>
      <button onClick={() => setCount(count + 1)}>{count}</button>
    </div>
  );
}

const ButtonBlock = block(Button);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        test
        <ButtonBlock />
      </main>
    </>
  );
}
